### ISSUE TITLE
SUpport for EP25 devices

### ISSUE THREAD

**Issue by JobyB** [computergeek1507/fpp-plugin-tplink#11]
Hi,

Would it be possible to add support for the EP25 devices? They are single plug controllers with current monitoring, and Apple HomeKit compatibility. Let me know if you need any further information or stuff tested.

Thanks

`root@fpp:~# kasa discover --show-unsupported                                                                                                                   
Discovering devices on 255.255.255.255 for 3 seconds                                                                                                           
Found unsupported device (tapo/unknown encryption): {'result': {'device_id': '2c91d2ef208dbfc1e625c4de11bbf796', 'owner': '946CB64D54E635410879E46D607F8A36', '
device_type': 'SMART.KASAPLUG', 'device_model': 'EP25(US)', 'ip': '192.168.10.177', 'mac': '5C-E9-31-9C-8E-1B', 'is_support_iot_cloud': True, 'obd_src': 'apple
', 'factory_default': False, 'mgt_encrypt_schm': {'is_support_https': False, 'encrypt_type': 'AES', 'http_port': 80, 'lv': 2}}, 'error_code': 0}               
                                                                                                                                                               
Found unsupported device (tapo/unknown encryption): {'result': {'device_id': 'c68615d2d34759c93a1fced9f54dd5d1', 'owner': '946CB64D54E635410879E46D607F8A36', '
device_type': 'SMART.KASAPLUG', 'device_model': 'EP25(US)', 'ip': '192.168.10.158', 'mac': '5C-E9-31-9C-82-B5', 'is_support_iot_cloud': True, 'obd_src': 'apple
', 'factory_default': False, 'mgt_encrypt_schm': {'is_support_https': False, 'encrypt_type': 'AES', 'http_port': 80, 'lv': 2}}, 'error_code': 0}               
                                                                                                                                                               
Found 0 devices                                                                                                                                                
Found 2 unsupported devices                                                                                                                                    
root@fpp:~#`

**Comment by JobyB** [comment]
Just tried again with the latest version, the MAC's ID and Hash were all fine I edited them for privicy:

TPLink Plugin Discovery: No host name given, trying discovery..
Discovering devices on 255.255.255.255 for 5 seconds
== Authentication failed for device ==
== Discovery Result ==
Device Type: SMART.KASAPLUG
Device Model: EP25(US)
IP: 192.168.10.177
MAC: 5C-
Device Id (hash): aaa
Owner (hash): xxx
HW Ver: None
Supports IOT Cloud: True
OBD Src: apple
Factory Default: False
Encrypt Type: AES
Supports HTTPS: False
HTTP Port: 80
LV (Login Level): 2


== Authentication failed for device ==
== Discovery Result ==
Device Type: SMART.KASAPLUG
Device Model: EP25(US)
IP: 192.168.10.146
MAC: 5C-
Device Id (hash): bbb
Owner (hash): xxx
HW Ver: None
Supports IOT Cloud: True
OBD Src: apple
Factory Default: False
Encrypt Type: AES
Supports HTTPS: False
HTTP Port: 80
LV (Login Level): 2


== Authentication failed for device ==
== Discovery Result ==
Device Type: SMART.KASAPLUG
Device Model: EP25(US)
IP: 192.168.10.158
MAC: 5C-
Device Id (hash): ccc
Owner (hash): xxx
HW Ver: None
Supports IOT Cloud: True
OBD Src: apple
Factory Default: False
Encrypt Type: AES
Supports HTTPS: False
HTTP Port: 80
LV (Login Level): 2


== Authentication failed for device ==
== Discovery Result ==
Device Type: SMART.KASAPLUG
Device Model: EP25(US)
IP: 192.168.10.205
MAC: 5C-
Device Id (hash): ddd
Owner (hash): xxx
HW Ver: None
Supports IOT Cloud: True
OBD Src: apple
Factory Default: False
Encrypt Type: AES
Supports HTTPS: False
HTTP Port: 80
LV (Login Level): 2


Found 0 devices
Found 4 devices that failed to authenticate

**Comment by computergeek1507** [comment]
The EP25 uses a different encryption and requires an authorization key from the Internet. I don't plan on supporting it anytime soon.

**Comment by JobyB** [comment]
Ok thanks for the update
