### ISSUE TITLE
Can't get it to run on K8-Pi on a Pi 4B

### ISSUE THREAD

**Issue by SopherConklin** [computergeek1507/fpp-plugin-tplink#12]
FPP 7.5
Install plugin - Discovery works
I make the dummy controller (I call it KASA-2plug) in xLights and assign a single line single light to it.
I FPP Connect and send that sequence to FPP
At this point I get
![image](https://github.com/user-attachments/assets/8b5b011c-11fc-49e6-b049-837ca41dfa2d)
I get this even if I have a different sequence selected.
At this time
 1.  Commands presets all work 
![image](https://github.com/user-attachments/assets/e6f8d428-30c9-495f-8e16-3d05cde04db3)
 2.  Pinging the KASA plug from the Channel Outputs page works  
![image](https://github.com/user-attachments/assets/85a9f0e9-8555-4716-9d71-bf9f5a7382e0)
 3.  Pinging plug from SSH shell works  
![image](https://github.com/user-attachments/assets/ea874064-9022-449b-b7e1-fba0453a30d8)

I got no errors on the plugin install.

Next I figured I had an error that was fixed with the update so I Update Plugin
There are no errors in the update  
![image](https://github.com/user-attachments/assets/cecda025-0df5-44d5-bdef-b44f17c562d7)

Now Discovery does nothing
![image](https://github.com/user-attachments/assets/4f77b51a-dfa2-4edb-8c32-5f127d849be8)
Command presets still turn the plug on and off
Pinging the plug from the Output Channels still works  
![image](https://github.com/user-attachments/assets/4536f008-72a3-434b-ac55-1739bc799568)

I still get the message that it can't ping the plug, and running the sequence doesn't turn the plug on and off

I'm a bit over my head in terms of what all you are doing and in terms of linux.  Can we do a Zoom and you can help me query the system to see what is going on?

Thanks for any help you can give.

**Comment by computergeek1507** [comment]
You don't setup the plugs as a DDP output.

**Comment by SopherConklin** [comment]
I didn't do that manually - it happened when I uploaded the sequence - do I just delete that DDP output?

**Comment by SopherConklin** [comment]
I deleted the plug DDP output and 
1.  Discovery still doesn't work
2. Pinging error message is gone
3. Playing the playlist does not turn the plugs on and off
Should I go back to just installing and not upgrading (when Discovery still worked) and upload the sequence, then delete the DDP output?

**Comment by SopherConklin** [comment]
Here is my controller file
<Vendor Name="FPP">
    <Controller Name="Pumpkin">
        
        <Variant Name="" ID="Pumpkin" Base="FPP:BaseFPPSettings">
            <SupportsVirtualStrings/>
            <SupportsAutoLayout/>
            <MaxPixelPort>0</MaxPixelPort>
            <MaxSerialPort>0</MaxSerialPort>
        </Variant>
    </Controller>
</Vendor>
Did I do something wrong that I don't see?
Here is my controller in xLights - I don't see a difference from yours, but I might have missed it.
![image](https://github.com/user-attachments/assets/103dfd2a-63e2-4dcc-8009-06c86a08dbe4)

**Comment by SopherConklin** [comment]
oops - my controller file
![image](https://github.com/user-attachments/assets/a75ce3a5-c0d2-4d18-bf1d-19c7f2862709)

**Comment by SopherConklin** [comment]
Is the IP address in the dummy controller the IP of the plug or is it the IP of the FPP which I installed the plugin to?

**Comment by SopherConklin** [comment]
Changed the IP of the dummy controller to be the IP of the controller I installed the plugin to, but no change.

**Comment by SopherConklin** [comment]
I noticed that in xLights you do have the controller which you installed the plugin to.   This is also the controller that we will use the IP address for the dummy controller.   I have both the controller which the plugin is installed to and the dummy controller in xLights and they both have the same IP address.  In xLights in the Dummy Controller settings, the IP is RED, which I suppose is due to 2 different controllers having the same IP address.    Can I not have my show player controller in xLights if I use that same address for the dummy controller?   Does that mean that I need a dedicated controller than only hosts the  plugin?

**Comment by SopherConklin** [comment]
Oops - in xLights you do NOT have the controller you installed the plugin to (...5.84)- this means you don't have the IP conflict that I have, but I need that controller to run my show - should I dedicate a pi to just host the plugin and become a "dummy controller" and use a different pi to run my K8-Pi?

**Comment by computergeek1507** [comment]
You would setup you main show controller as the "dummy" controller

**Comment by SopherConklin** [comment]
How does the "dummy" controller run my K8-Pi?   How do I assign props to various outputs of my show controller if it is a "dummy" with no ports?   I'm pretty new at this but I don't understand

**Comment by computergeek1507** [comment]
You wouldn't create a "dummy" controller. You have to assign the single lined Model in xLights to an unused port in the k8, it can be the dmx port if needed, then change the channel number in the Kasa Config tab to match it

**Comment by SopherConklin** [comment]
Okay, great - that worked.  I am very grateful to you for writing this plugin, which solves a problem for me, but the documentation isn't clear to a beginner like me.

**Comment by SopherConklin** [comment]
Also, it appears either an Off effect or no effect turns the plug off.   Thanks again for your help.

**Comment by SopherConklin** [comment]
I would suggest something like this works for newbies like me.
[FPP TP-Link KASA plugin by Scott Hanson.txt](https://github.com/user-attachments/files/16575754/FPP.TP-Link.KASA.plugin.by.Scott.Hanson.txt)

**Comment by computergeek1507** [comment]
I understand it's not easy to configure, I personally only use commands. Due to limitations in xLights/FPP, plugins and non standard output types can't use Auto layout/visualizer and upload. I have thought about tying outputs to models to help with the start channel issue. When no effect is "on" FPP will send a zero which will turn it off. Anything above 127 will turn it on.

**Comment by SopherConklin** [comment]
I think it's great that this is possible - I intend to turn the 12 foot skeleton/pumpkin and the giant spider on and off at various times within my Halloween sequences, so this is great.

P.S.  I didn't upgrade the plugin since the Discovery and everything else works now and Discovery doesn't work after the upgrade and I don't know if everything else would work or not!

Thanks again for making this plugin - it will really add to my sequences and it would be completely impossible for me to do myself!
