### ISSUE TITLE
fpp-plugin-tplink.log contains only "c++"

### ISSUE THREAD

**Issue by jpkroeker** [computergeek1507/fpp-plugin-tplink#3]
I was hoping to use the tplink plugin log file to help figure out why my tplink test sequence doesn't work.  The only entries in the log are lines containing the text "c++".   I can upload the log file if needed, but since there isn't much in it, I haven't bothered.

I set the log levels to debug and excessive just to make sure it wasn't dependent on logging level.

**Comment by computergeek1507** [comment]
The plugin logs to the standard fppd.log

**Comment by jpkroeker** [comment]
Ok, if that's how you intended it, I will close the issue.
