### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by Plateump** [computergeek1507/fpp-plugin-tplink#4]
Installing plugin fpp-plugin-tplink
Cloning into 'fpp-plugin-tplink'...
Running fpp_install.sh script for fpp-plugin-tplink
Building FPP on 'Raspberry Pi' platform
ccache g++ -fpch-preprocess -O3 -Wno-psabi -pipe -I /opt/fpp/src -fpic -std=gnu++2a -I/opt/fpp/src -c src/tplinkPlugin.cpp -o src/tplinkPlugin.o
src/tplinkPlugin.cpp:29:10: fatal error: channeloutput/channeloutput.h: No such file or directory
   29 | #include "channeloutput/channeloutput.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:11: src/tplinkPlugin.o] Error 1
{"Status":"Error","Message":"Could not properly install plugin"}

**Comment by computergeek1507** [comment]
fixed with 858acb5836ef6711d6c5c1af1e64fce17167f143
